# -*- coding: utf-8 -*-
"""Devlope the python code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZyHUukSTY6AVIxvj0x-4QsxILXwCgTjC
"""

import  time
import  os
import  datetime
import  random

myconfig = {
                "identity":
                          {
                               "orgId": "2pgtcy",
                              "typeId": "node2-mcu",
                              "deviceId": "60034009"
                          },
               "auth" :{
                   "token": "bOK-_zPjpShDHMx*kc"
               }            
                  
               }


#client = wiotp.sdk.device.DeviceClient(config==myConfig, loghandlers=None)  
#client.connect()
#client = wiotp.sdk.device.DeviceClient(config=myConfig)

 def myCommandCallback(cmd):
  print("Message received from IBM IoT Platform:%s" % cmd.data['command'])
  m=cmd.data['command']
  if(m =="motoron"):
    print("Motor is switched on")
  elif(m=="motoroff"):
    print("Motor is switched OFF")
    print(" ")

      while True:
      soil=random.randint(0,100)
      temp=random.randint(-20,125)
      hum=random.randint(0,100)
      myData={'soil_moisture':soil, 'temperature':temp, 'humidity':hum}
      client.publishEvent(eventId="status",msgFormat="json", data=myData, qos=0, onPublish=None)
      print("Published data Successfully: %s", myData)
      time.sleep(2)
      client.commandCallback = myCommandCallback
      client.disconnect()
import  time
import  os
import  datetime
import  random

myconfig = {
                "identity":
                          {
                               "orgId": "2pgtcy",
                              "typeId": "node2-mcu",
                              "deviceId": "60034009"
                          },
               "auth" :{
                   "token": "bOK-_zPjpShDHMx*kc"
               }            
                  
               }


#client = wiotp.sdk.device.DeviceClient(config==myConfig, loghandlers=None)  
#client.connect()
#client = wiotp.sdk.device.DeviceClient(config=myConfig)

 def myCommandCallback(cmd):
  print("Message received from IBM IoT Platform:%s" % cmd.data['command'])
  m=cmd.data['command']
  if(m =="motoron"):
    print("Motor is switched on")
  elif(m=="motoroff"):
    print("Motor is switched OFF")
    print(" ")

      while True:
      soil=random.randint(0,100)
      temp=random.randint(-20,125)
      hum=random.randint(0,100)
      myData={'soil_moisture':soil, 'temperature':temp, 'humidity':hum}
      client.publishEvent(eventId="status",msgFormat="json", data=myData, qos=0, onPublish=None)
      print("Published data Successfully: %s", myData)
      time.sleep(2)
      client.commandCallback = myCommandCallback
      client.disconnect()